#!/bin/bash
# Check layer boundary violations for TS/JS projects
# Generated by harness-engineering based on engineering-structure.md
# PostToolUse contract: violations exit 2 with the message on stderr; exit 0 otherwise.
FILE="$1"

# Determine which layer this file belongs to
# (Based on directory structure detected in Phase 1)
LAYER=""
case "$FILE" in
  */routes/*|*/pages/*|*/app/*)   LAYER="route" ;;
  */services/*)                    LAYER="service" ;;
  */models/*|*/entities/*)         LAYER="model" ;;
  */repositories/*|*/db/*)         LAYER="repository" ;;
  */adapters/*|*/clients/*)        LAYER="adapter" ;;
  *)                               exit 0 ;;  # Unknown layer, skip
esac

# Check forbidden imports per layer
# (Generated from Layer Boundaries table in engineering-structure.md)
case "$LAYER" in
  route)
    # Routes must not import directly from repository/adapter.
    # Matches ESM `from '...'` AND CJS `require('...')`/dynamic `import('...')`.
    if grep -qE "(from|require\(|import\()\s*['\"].*/(repositories|adapters|db)/" "$FILE" 2>/dev/null; then
      {
        echo "LAYER VIOLATION: Route layer cannot import from repository/adapter layer"
        echo "File: $FILE"
        echo "Fix: Route should call service, service calls repository"
      } >&2
      exit 2
    fi
    ;;
  service)
    # Services must not import from route layer (ESM + CJS + dynamic import).
    if grep -qE "(from|require\(|import\()\s*['\"].*/(routes|pages|app)/" "$FILE" 2>/dev/null; then
      {
        echo "LAYER VIOLATION: Service layer cannot import from route layer"
        echo "File: $FILE"
      } >&2
      exit 2
    fi
    ;;
esac

exit 0
